name: Todo Fronted Pipeline

on:
    push:
        branches:
            - master
        paths:
            - .github/**
            - docker/**
            - nginx/nginx.conf
            - public/**
            - src/**
            - package.json

jobs:
    build-image:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
          
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Extract project version
              id: extract_version
              run: |
                apt-get update && apt-get install -y jq
                echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

            - name: Login to Docker registry
              run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build docker image 
              run: |
                docker build --build-arg VITE_APP_API_URL=${{secrets.API_URL}} \
                -t ${{secrets.DOCKERHUB_USERNAME}}/todo-ui:${{steps.extract_version.outputs.VERSION}} \
                -f docker/Dockerfile . \

            - name: Push image to regsitry
              run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/todo-ui:${{steps.extract_version.outputs.VERSION}}

                 

    
